### ISSUE TITLE
Not working as of Webstorm version 2018.1.6

### ISSUE THREAD

**Issue by dlarr** [alp82/idea-tabsession#7]
Hello, I am trying this becaus there is still no way to have all terminals saved with names and paths.

Tried the plugin on version : 
![image](https://user-images.githubusercontent.com/2865021/44328219-41f29500-a461-11e8-897c-870bbc87666d.png)

Problem : 
No save and load menus are added. Therefore I am not able to save the tab session.

Best regards,
Denis.

**Comment by alp82** [comment]
I am very sorry, but this project is discontinued because IDEA (and presumably Webstorm too) have support for the same features of this plugin, please see the top of the [README](https://github.com/alp82/idea-tabsession) for more information.

The plugin didn't save terminals anyway, only editor tabs. I am not aware of anything that can restore open terminals.

**Comment by dlarr** [comment]
Hello and thanks for answering.

Webstorm does have the save/load context stuff. But it doesn't save anything about terminals.

I know about that ticket for IntelliJ asking for this particular feature : save tab names and paths ( https://youtrack.jetbrains.com/issue/IDEA-117946 )

Thing is the ticket is 5 years old, which mean if we want the stuff we need to do it ourselves ^^

I though your lib had a solo purpose : save terminals ! :)

Thanks anyway.

Regards,
Denis.

**Comment by alp82** [comment]
Sorry to disappoint, but you may want to clone the repo and try it by yourself. Not sure how complex your feature request is though.

**Comment by dlarr** [comment]
Hehe I should give it a try, not sure if have the time for it ! :> thanks a lot anyway !

Cheers !
